#!/usr/bin/env python3
"""PreToolUse(Edit|Write|MultiEdit|NotebookEdit): protect secrets, lockfiles and the guardrails themselves."""
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from _common import block, project_dir, read_event, rel  # noqa: E402

SECRET_PATTERNS = {
    "AWS access key": r"AKIA[0-9A-Z]{16}",
    "private key": r"-----BEGIN (RSA |EC |OPENSSH |DSA )?PRIVATE KEY-----",
    "GitHub token": r"\b(ghp_[A-Za-z0-9]{36}|github_pat_[A-Za-z0-9_]{40,})",
    "Stripe live key": r"\b(sk|rk)_live_[A-Za-z0-9]{16,}",
    "OpenAI/Anthropic-style API key": r"\bsk-(proj-|ant-)?[A-Za-z0-9_\-]{32,}",
    "Slack token": r"\bxox[abprs]-[A-Za-z0-9-]{10,}",
    "Google API key": r"\bAIza[0-9A-Za-z_\-]{35}",
}
LOCKFILES = {"package-lock.json", "pnpm-lock.yaml", "yarn.lock", "bun.lockb", "poetry.lock", "uv.lock",
             "Pipfile.lock", "pubspec.lock", "Cargo.lock", "Gemfile.lock"}
PROTECTED_PREFIXES = (".claude/hooks/", ".githooks/")
PROTECTED_FILES = {".claude/settings.json", ".claude/quality-gate.json"}


def new_content(tool_input: dict) -> str:
    parts = [tool_input.get("content") or "", tool_input.get("new_string") or "", tool_input.get("new_source") or ""]
    for e in tool_input.get("edits") or []:
        parts.append(e.get("new_string") or "")
    return "\n".join(parts)


def main() -> None:
    event = read_event()
    ti = event.get("tool_input") or {}
    path = ti.get("file_path") or ti.get("notebook_path") or ""
    root = project_dir(event)
    r = rel(path, root)
    name = Path(path).name

    if re.fullmatch(r"\.env(\..+)?", name) and name != ".env.example":
        block(f"`{r}` holds real secrets and only the owner edits it. Add the variable NAME (no value) to "
              "`.env.example`, then tell the owner in plain words: which key, where to get it, where to paste it.")

    if name in LOCKFILES:
        block(f"`{name}` is generated by the package manager. Change dependencies with the package manager "
              "(e.g. `npm install <pkg>`), never by hand.")

    guard_unlocked = (root / ".claude" / "ALLOW_GUARDRAIL_EDITS").exists() or os.environ.get("ALLOW_GUARDRAIL_EDITS") == "1"
    if (r in PROTECTED_FILES or r.startswith(PROTECTED_PREFIXES)) and not guard_unlocked:
        block(f"`{r}` is part of the project's safety net. Don't weaken or bypass it to make something pass. "
              "If a change is genuinely needed, explain why to the owner; they can unlock edits by creating "
              "the file `.claude/ALLOW_GUARDRAIL_EDITS` (and deleting it afterwards).")

    content = new_content(ti)
    for label, pattern in SECRET_PATTERNS.items():
        if re.search(pattern, content):
            block(f"This change contains what looks like a real {label}. Secrets must never be written into code. "
                  "Read it from an environment variable (process.env / os.environ) and list the name in `.env.example`.")
    sys.exit(0)


if __name__ == "__main__":
    main()
